///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;

namespace Mazegame.Entity {
	public class Player : Character {

        private Location currentLocation;

		public Mazegame.Entity.Location m_Location;

	    public Player()
	    {
	    }

	    public Player(String name) : base(name)
		{
		    
		}
        public Location CurrentLocation
        {
            get { return currentLocation; }
            set { currentLocation = value; }
        }


	}//end Player

}//end namespace Entity